name: report SDL

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      SDLe_id:
        required: true
        type: string

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input project and SDLe id to STDOUT
        run: |
          echo The project is ${{ inputs.project }}
          echo The SDLE id is ${{ inputs.SDLe_id }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the runner
        run: echo Building

  test:
    runs-on: ubuntu-latest
    steps: 
      - names: Test the project SDL
        run: testing

  scan:
    runs-on: ubuntu-latest
    steps: 
      - names: Scan the project SDL code
        run: scanning

  verify-tests:
    runs-on: ubuntu-latest
    steps: 
      - names: verify test results
        run: verifying tests

  verify-scans:
    runs-on: ubuntu-latest
    steps: 
      - names: verify the scans of code
        run: verifying scans

  upload-SDL-report:
    runs-on: ubuntu-latest
    steps: 
      - names: Upload the evidence to the project SDL
        run: uploading SDL