name: report SDL

on:
  workflow_call:
    inputs:
      project:
        description: 'The project that its gonna be tested'
        default: 'EMA'
        required: true
        type: string
      SDLe_id:
        description: 'the SDLe ID'
        default: 0
        required: true
        type: int

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input project and SDLe id to STDOUT
        run: |
          echo The project is ${{ inputs.username }}
          echo The SDLE id is ${{ inputs.SDLe_id }}