name: report SDL

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'The project that you want to test & scan'
        required: true
        type: choice
        options:
        - 'EMA'
        - 'UNITE'
      job:
        description: 'What do you want to execute'
        required: true
        type: choice
        options: 
        - 'run All'
        - 'run tests'
        - 'run scans'
      SDLe_id:
        description: 'The ID of the SDL project'
        required: true
        type: string
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

jobs:
  print-info:
    if: ${{ inputs.print_tags }}
    runs-on: ubuntu-latest
    steps:
      - name: Print the input project and SDLe id to STDOUT
        run: |
          echo The project is ${{ inputs.project }}
          echo The job is ${{ inputs.job}}
          echo The SDLE id is ${{ inputs.SDLe_id }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the runner
        run: echo Building

  test:
    if: ${{input.job == 'run All' || input.job == 'run tests'}}
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Test the project SDL
        run: echo testing

  scan:
    if: ${{input.job == 'run All' || input.job == 'run scans'}}
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Scan the project SDL code
        run: echo scanning

  verify-tests:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: verify test results
        run: echo verifying tests

  verify-scans:
    needs: scan
    runs-on: ubuntu-latest
    steps: 
      - name: verify the scans of code
        run: echo verifying scans

  upload-SDL-report:
    if: ${{ always() }}
    needs: [verify-tests, verify-scans]
    runs-on: ubuntu-latest
    steps: 
      - name: Upload the evidence to the project SDL
        run: echo uploading SDL