name: report SDL

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      SDLe_id:
        required: true
        type: number

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input project and SDLe id to STDOUT
        run: |
          echo The project is ${{ inputs.username }}
          echo The SDLE id is ${{ inputs.SDLe_id }}